In [2]:
import pandas as pd

df = pd.read_csv("data_box_office.csv")

df.head()

,Unnamed: 0,budget,cast,close,director,gross,mpaa,open,opening_gross,opening_theaters,...,June-Sep,Oct-Nov,Jan-May,Dec,mpaa_new,PG,R,PG-13,prol_studio,Tier_2
0,2978462,36000000.0,NaN,12/18,NaN,42024533.0,Rated PG for some mild thematic elements,9/12,15873397.0,3656.0,...,True,False,False,False,PG,True,False,False,False,False
1,1571222,20000000.0,NaN,5/3,NaN,5704709.0,Rated R for sexual content and brief language,11/23,167953.0,4.0,...,False,True,False,False,R,False,True,False,False,False
2,1920849,3000000.0,NaN,10/11,NaN,447954.0,"Rated R for sexual content, pervasive language...",9/7,181494.0,47.0,...,True,False,False,False,R,False,True,False,False,False
3,1220634,57500000.0,NaN,11/4,NaN,60128566.0,Rated R for sequences of strong violence and l...,9/10,26650264.0,3203.0,...,True,False,False,False,R,False,True,False,False,False
4,2295722,4500000.0,NaN,9/11,NaN,11774.0,"Rated R for violence throughout, and some sexu...",9/5,8691.0,10.0,...,True,False,False,False,R,False,True,False,False,False

In [3]:
#remove uninteresting columns
clean = df.drop(['cast','close', 'director', 'mpaa', 'open', 'rank', 'June-Sep', 'Oct-Nov', 'Jan-May', 'Dec', 'PG', 'R', 'PG-13', 'prol_studio', 'Tier_2'], axis=1)
print(clean.columns)
id = clean.columns.get_loc('rating')
print(id)

Index(['Unnamed: 0', 'budget', 'gross', 'opening_gross', 'opening_theaters',
       'rating', 'season', 'studio', 'title', 'year', 'mpaa_new'],
      dtype='object')
5

In [27]:
#Dataset for an Ensemble of Naive bayes classifiers
#from sklearn.preprocessing import KBinsDiscretizer
import numpy as np
def discretize(df, nofbuckets=5):
   # Disc = KBinsDiscretizer(n_bins=nofbuckets, encode='ordinal', strategy='uniform')
    aux = pd.qcut(list(range(df['budget'].min,df['budget'].max+1)), nofbuckets, labels=['cheap', 'cheapish' ,'medium', 'pricish','pricy'])
    print(aux)
    
    #df['gross'] = pd.cut(df['gross'], nofbuckets[1])
    #df['opening_gross'] = pd.cut(df['opening_gross'], nofbuckets[2])
    #df['opening_theaters'] = pd.cut(df['opening_theaters'], nofbuckets[3])
    #df['rating'] = pd.cut(df['rating'], nofbuckets[4])
    
    
discretize(clean)

TypeError: unsupported operand type(s) for +: 'method' and 'int'

In [10]:
print(int(clean['budget']))
#converter para inteito o maximo +1 de cada coluna para definir o range

TypeError: cannot convert the series to <class 'int'>